# Generated by Django 4.1.7 on 2023-03-09 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fname', models.CharField(max_length=20)),
                ('Lname', models.CharField(max_length=20)),
                ('Age', models.IntegerField(null=True)),
                ('Bloodgroup', models.CharField(choices=[('A+ve', 'A+ve'), ('B+ve', 'B+ve'), ('AB+ve', 'AB+ve'), ('O+ve', 'O+ve')], max_length=25, null=True)),
            ],
        ),
    ]
