# Generated by Django 4.1.2 on 2023-03-13 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blood',
            name='Date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
